<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>TweetSweep</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- styles -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/tweetsweep.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      #user-table td{
        padding: 5px;
      }
      #tags{
        /*margin-top:10px;*/
      }
      #tags ul{
        list-style:none;
      }
      #tags > ul{
        margin-top:10px;
        margin-left:0px;
      }
    </style>
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/base/jquery-ui.css" rel="stylesheet">

    <!--  HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    {% include 'components/navigation.phtml' %}

    <div class="container">
      <div class="row">
        <div class="span7">
          <h1 id="1">Origins of TweetSweep</h1></br>
          <p>TweetSweep originated from the Collaborative Innovation in Journalism and Technology class at Northwestern University during Spring 2012.</br></br>
          The project, originally called Hashtag Helper, was envisioned by professors Rich Gordon, Larry Birnbaum, and Darnell Little as a simple tool to help publishers increase content visibility through Twitter.</br></br>
          Team TweetSweep consists of graduate journalism student Christi Sodano and computer science students Andrew Allen, Wesley Sun, and Jessie Li.
</p>
</br>
          <h2><strong>How It Works</strong></h2>
      <div>
           TweetSweep users will compose a tweet with an accompanying link to relevant written content. Users can manipulate the number of tweets analyzed and opt to analyze the entire article or simply the headline depending on their needs.</br></br>
           
           By entering relevant terms within the search field, TweetSweep will better refine the Twitter query.</br></br>
           
           Next, users can select from suggested hashtag recommendations or at-mention recommendations to get a snapshot of trends on Twitter.
           By clicking the "+" button the user will append desired hashtag recommendations or at-mention recommendations to the tweet.</br></br>
            
    	   TweetSweep publishes the tweet along with an abbreviated link to content.
    	   </div>
        <div class="span5"><img src="img/howitworks.png"></div>
      </div>
      


      <hr/>
      <footer>
        <p>© TweetSweep 2012</p>
      </footer>
    </div>





    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script src="js/bootstrap.js"></script>



  </body>
</html>
