<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>TweetSweep</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- styles -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/tweetsweep.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      #user-table td{
        padding: 5px;
      }
      #tags{
        /*margin-top:10px;*/
      }
      #tags ul{
        list-style:none;
      }
      #tags > ul{
        margin-top:10px;
        margin-left:0px;
      }
    </style>
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/base/jquery-ui.css" rel="stylesheet">

    <!--  HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    {% include 'components/navigation.phtml' %}

    <div class="container">
      <div class="row">
        <div class="span7">
          <h1 id="1">The Origins of TweetSweep</h1>
          <p>TweetSweep originated from the Collaborative Innovation in Journalism and Technology class at Northwestern University during Spring 2012. The
          project, originally called Hashtag Helper, was envisioned by professors Rich Gordon, Larry Birnbaum, and Darnell Little as a simple tool to help publishers increase content visibility through Twitter.</br> 
          Team TweetSweep consists of graduate journalism student Christi Sodano and computer science students Andrew Allen, Wesley Sun, and Jessie Li.
</p>
</br>
          <h2><strong>How It Works:</strong></h2>
          <ul>
            <li><strong>STEP 1: Compose</strong></br>Compose a tweet with an accompanying link to your article or content.</li></br>
            <li><strong>STEP 2: Browse</strong></br>Browse through and select from the suggested category tags that are relevant. Adjust the number of analyzed tweets. </li></br>
            <li><strong>STEP 3: View</strong></br>Select from the hashtag recommendations or at-mention recommendations to get a snapshot of user tweeting trends via the TweetSweep visualization.</li></br>
            <li><strong>STEP 4: Add</strong></br>Click the "+" button to append hashtag recommendations or at-mention recommendations to the tweet.</li></br>
            <li><strong>STEP 5: Tweet</strong></br>Click <strong>Tweet</strong> and TweetSweep publishes your tweet along with a shortened link to content.</li>
          </ul>
        </div>
        <div class="span5"><img src="http://placehold.it/500x400"></div>
      </div>
      


      <hr/>
      <footer>
        <p>© TweetSweep 2012</p>
      </footer>
    </div>





    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script src="js/bootstrap.js"></script>



  </body>
</html>
