<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>TweetSweep</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- styles -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/tweetsweep.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      #user-table td{
        padding: 5px;
      }
      #tags{
        /*margin-top:10px;*/
      }
      #tags ul{
        list-style:none;
      }
      #tags > ul{
        margin-top:10px;
        margin-left:0px;
      }
    </style>
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/base/jquery-ui.css" rel="stylesheet">

    <!--  HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    {% include 'components/navigation.phtml' %}

    <div class="container">
      <div class="row">
        <div class="span7">
          <h1 id="1">Contact TweetSweep</h1>
          <div class="contacts">
        
        <h3>Andrew Allen</h3>
      	@_andrew_allen_</br>
        <img src="http://placehold.it/100x120"></p> 
        <h3>Jessie Li</h3>
        @rawr_its_jessie</br>
        <img src="img/jessieli.jpg" height="100" width="120"></p>
        <h3>Christi Sodano</h3>
        <p>@ChristiSodano</br>
        <img src="img/Reporter Photo Copy.jpg" height="100" width="120"></p>
        <h3>Wesley Sun</h3>
        <p>@weaslesun</br>
        <img src="img/wessun.jpg" height="100" width="120"> </p>
        
          
        <p id="mailto">For more information email us at <a href="mailto:info@tweetsweep.net">
		info@tweetsweep.net</a></p>  
          </div>
        </div>
      </div>


      <hr/>
      <footer>
        <p>© TweetSweep 2012</p>
      </footer>
    </div>





    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script src="js/bootstrap.js"></script>



  </body>
</html>
