<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>TweetSweep</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- styles -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/tweetsweep.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      #user-table td{
        padding: 5px;
      }
      #tags{
        /*margin-top:10px;*/
      }
      #tags ul{
        list-style:none;
      }
      #tags > ul{
        margin-top:10px;
        margin-left:0px;
      }
    </style>
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/base/jquery-ui.css" rel="stylesheet">

    <!--  HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    {% include 'components/dashboard_nav.phtml' %}

    <div class="container-fluid">
      <div class="row-fluid">

        <div class="span3">
      <div class="span3 well" style="padding:0">
        <table id="user-table" style="width:100%;">
          <tr>
            <td><img src="{{profile_image_url}}"</td>
            <td><strong>{{name}}</strong><br/>{{location}}</td>
          </tr>
          <tr style="border-top:1px solid #e8e8e8; border-bottom:1px solid #e8e8e8;">
            <td><strong>{{tweets_count}}</strong><br/>Tweets</td>
            <td style="border-left: 1px solid #e8e8e8;border-right: 1px solid #e8e8e8;">
              <strong>{{following_count}}</strong><br/>Following</td>
            <td><strong>{{followers_count}}</strong><br/>Followers</td>
          </tr>
          <tr>
            <td colspan="3">
              <textarea class="" id="composition-textarea" rows="3" style="width:96%" placeholder="Compose new tweet..."></textarea>
              <div class="input-prepend">
                <span class="add-on"><i class="icon-file"></i></span>
                <input class="span2 link-input" id="inputIcon" type="text" style="width:220px">
              </div>
              <div style="text-align:right;">
                <span id="chars-remaining">140</span>
                <button id="tweet-btn" class="btn btn-info disabled">Tweet</button>
              </div>
            </td>
          </tr>
        </table>

      </div> <!-- span3 -->
      <!-- id="usertimeline" -->
      <div id="" class="span3 well" style="padding:0;height:350px;overflow:auto;">
      
       <h4>Tags:</h4>
        <div id="tags"></div>

      </div> <!-- span3 -->
    </div>
    
      <div class="span6" style="margin-left:0">
        
        <div id="result" class="span6 well" style="height:552px"> </div>
      </div>
      <div class="span2 well" style="margin-left:4%">
        <div class="demo">

        <p>
          <label for="amount">Twitter Results:</label>
          <input type="text" id="amount" style="border:0; color:#f6931f; font-weight:bold; width:50px" />
        </p>

        <div id="slider"></div>

        </div><!-- End demo -->
        <br/>
        
      </div>
      <!-- <a id="testButton" class="btn" data-toggle="modal" data-contents="#masters" href="#myModal" >Launch Modal</a> -->

      <!-- <ul>
        <li><a href="?authenticate=1">Sign in with Twitter</a></li>
        <li><a href="?authenticate=1&amp;force=1">Sign in with Twitter (force login)</a></li>
        <li><a href="?authorize=1">Authorize Application (with callback)</a></li>
        <li><a href="?authorize=1&amp;oob=1">Authorize Application (oob - pincode flow)</a></li>
        <li><a href="?authorize=1&amp;force_read=1">Authorize Application (with callback) (force read-only permissions)</a></li>
        <li><a href="?authorize=1&amp;force_write=1">Authorize Application (with callback) (force read-write permissions)</a></li>
        <li><a href="?authorize=1&amp;force=1">Authorize Application (with callback) (force login)</a></li>
        <li><a href="?wipe=1">Start Over and delete stored tokens</a></li>
      </ul> -->
    </div> <!-- /row -->

    </div> <!-- /container -->

    {% include 'components/modal.phtml' %}

    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/tweetsweep.js"></script>
    <script src="js/flot/jquery.flot.js"></script>

    <script src="js/flot-tweetsweep.js"></script>

    <script type="text/javascript">
      //$('#myModal').modal();
      //$('#myModal').modal('hide');
    </script>
   


  </body>
</html>
