<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>TweetSweep</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- styles -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/tweetsweep.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      #user-table td{
        padding: 5px;
      }
      #tags{
        /*margin-top:10px;*/
      }
      #tags ul{
        list-style:none;
      }
      #tags > ul{
        margin-top:10px;
        margin-left:0px;
      }
    </style>
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/base/jquery-ui.css" rel="stylesheet">

    <!--  HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    {% include 'components/navigation.phtml' %}

    <div class="container">
      <div class="row">
        <div class="span7">
          <h1 id="1">Recon</h1></br>
          <p>TweepSweep is a publishing tool used to optimize the reach of a tweet with linked content. TweetSweep's recon capabilities use natural language APIs to compare written content against the most popular Twitter trends and users. Its easy-to-use dashboard allows publishers insight into the most popular trends while still allowing room for editorial judgement.</p>
          </ul>
        </div>
       <div class="span5"><img src="http://placehold.it/300x300"></div>
      </div>
      <hr/>
      <div class="row">
        <div class="span7">
        
         <h1 id="2">Reach</h1></br>
          <p>Once the appropriate fields have been entered, TweetSweep provides publishers with the number of uses for each trending hashtag or at-mention. Publishers are free to select the most appropriate hashtags or at-mentions from the list of reccommended options and append theit desired options to their tweet. </p>
         <!-- <ul>
            <li>Lorem ipsum dolor</li>
            <li>consectetur adipisicing elit</li>
            <li>labore et dolore magna aliqua</li>
            <li>eu fugiat nulla pariatur</li>
          </ul> -->
        </div>
        <div class="span5"><img src="http://placehold.it/300x300"></div>
      </div>
      <hr/>
      <div class="row">
        <div class="span7">
          <h1 id="3">Reflection</h1></br>
          <p>Using our easy-to-understand data visualization, publishers can monitor a trend's usage over the previous eight days, allowing them to assess whether the hashtags or at-mentions they selected extended the reach of their content.</p>
          <!--<ul>
            <li>Lorem ipsum dolor</li>
            <li>consectetur adipisicing elit</li>
            <li>labore et dolore magna aliqua</li>
            <li>eu fugiat nulla pariatur</li>
          </ul> -->
        </div>
        <div class="span5"><img src="http://placehold.it/300x300"></div>
        
      </div>


      <hr/>
      <footer>
        <p>© TweetSweep 2012</p>
      </footer>
    </div>





    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script src="js/bootstrap.js"></script>



  </body>
</html>
