<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"><img src="logos/tweetsweep5.png" height="100" width="150"/></a>
          <div class="nav-collapse">
            <ul class="nav">
              {% for item in navigation %}
                {% if item.page == page %}
                  {% set active = 'active' %}
                {% endif %}
                <li class="{{active}}"><a href="{{ item.href }}">{{ item.caption }}</a></li>
                {% set active = '' %}
              {% endfor %}
              <li class="divider-vertical"></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Feedback <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="https://docs.google.com/spreadsheet/viewform?formkey=dFotaVZqaG5odEROeUUwMWhaZlBMY0E6MQ#gid=0" target="_blank">Report a Bug</a></li>
                  <li><a href="https://docs.google.com/spreadsheet/viewform?formkey=dGhaQnhKVm5SRTgwSWhveXhrZFhtMVE6MQ#gid=0" target="_blank">Take the Survey</a></li>
                </ul>
              </li>

             
            </ul>
            
            <ul class="nav pull-right">
              <form id="search-form" class="navbar-search" action="">
              <input type="text" class="search-query span2" placeholder="Search">
            </form>
            <!-- <li><a href="#">Link</a></li> -->
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="?authenticate=1">Log in with twitter</a></li>
                <li><a href="?authorize=1">Authorize application</a></li>
                <li><a href="#">View Profile</a></li>
                <li class="divider"></li>
                <li><a href="?wipe=1">Log out</a></li>
              </ul>
            </li>
          </ul>
          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>