<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">TweetSweep</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="{{root}}">Home</a></li>
              <li><a href="{{root}}/?p=about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="divider-vertical"></li>
              <li><a href="#">Recon</a></li>
              <li><a href="#">Reach</a></li>
              <li><a href="#">Reflection</a></li>
             
            </ul>
            
            <ul class="nav pull-right">
              <form id="search-form" class="navbar-search" action="">
              <input type="text" class="search-query span2" placeholder="Search">
            </form>
            <!-- <li><a href="#">Link</a></li> -->
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="?authenticate=1">Log in with twitter</a></li>
                <li><a href="?authorize=1">Authorize application</a></li>
                <li><a href="#">View Profile</a></li>
                <li class="divider"></li>
                <li><a href="?wipe=1">Log out</a></li>
              </ul>
            </li>
          </ul>
          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>