 <div id="myModal" class="modal hide fade">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h3>#Hashtag Details</h3>
  </div>
  <div class="modal-body">
    <div id="flot" style="width:420px;height:200px;"></div>
    

    <hr>

    <table id="user-table" style="width:100%;">
          <tbody><tr>
            <td><h4>Tweets</h4></td>
            
          </tr>
    <!-- <pre> -->
      <!-- </pre> -->
<tr style="border-top:1px solid #e8e8e8; border-bottom:1px solid #e8e8e8;">
  <td>
    <img src="https://twimg0-a.akamaihd.net/profile_images/1744682717/Cubs_Logo_normal.jpg">
  </td>
  <td>
    <div><strong>Chicago Cubs </strong>@Cubs</div>
    <p class="js-tweet-text">Tonight's <a href="/#!/search/%23Cubs" title="#Cubs" class="  twitter-hashtag pretty-link" data-query-source="hashtag_click"><s><strong>#</strong></s><strong><b>Cubs</b></strong></a> vs. <a href="/#!/search/%23Reds" title="#Reds" class="  twitter-hashtag pretty-link" data-query-source="hashtag_click"><s>#</s><b>Reds</b></a> game in Cincinnati has been postponed due to rain. A makeup date has not been announced.</p>
    <small><a href="https://twitter.com/#!/Cubs/status/197495131060977664">1 May</a>     <span>via Twitter for iPhone</span></small>
  </td>
</tr>



  <!-- <pre> -->
      <!-- </pre> -->
<tr style="border-top:1px solid #e8e8e8; border-bottom:1px solid #e8e8e8;">
  <td>
    <img src="https://twimg0-a.akamaihd.net/profile_images/1928143605/BB_Twitter_normal.png">
  </td>
  <td>
    <div><strong>Bullpen Brian </strong>@bullpenbrian</div>
    <p class="js-tweet-text"><a class="  twitter-atreply pretty-link" data-screen-name="cliffy46405" href="/#!/cliffy46405" rel="nofollow"><s>@</s><b>cliffy46405</b></a> Trying to hang our hat on something positive for DeWitt--beside his beard! <a href="/#!/search/%23Cubs" title="#Cubs" class="  twitter-hashtag pretty-link" data-query-source="hashtag_click"><s><strong>#</strong></s><strong><b>Cubs</b></strong></a></p>
    <small><a href="https://twitter.com/_andrew_allen_/189511565081456640">2 May</a>     <span>via HootSuite</span></small>
  </td>
</tr>



  <!-- <pre> -->
      <!-- </pre> -->
<tr style="border-top:1px solid #e8e8e8; border-bottom:1px solid #e8e8e8;">
  <td>
    <img src="https://twimg0-a.akamaihd.net/profile_images/87216862/DSCF1595_normal.jpg">
  </td>
  <td>
    <div><strong>Phil Rizzuto </strong>@philrizzuto</div>
    <p class="js-tweet-text">Great foul ball seats! ( <a href="/#!/search/%23reds" title="#reds" class="  twitter-hashtag pretty-link" data-query-source="hashtag_click"><s>#</s><b>reds</b></a> vs <a href="/#!/search/%23cubs" title="#cubs" class="  twitter-hashtag pretty-link" data-query-source="hashtag_click"><s><strong>#</strong></s><strong><b>cubs</b></strong></a> game w/ <a href="http://t.co/r6gtFeMA" data-expanded-url="http://MLB.com" title="http://MLB.com" target="_blank" rel="nofollow" class="twitter-timeline-link" data-ultimate-url="http://mlb.mlb.com/index.jsp">MLB.com</a> <a href="http://t.co/AQGBq0G8" data-expanded-url="http://m.mlb.com/apps" title="http://m.mlb.com/apps" target="_blank" rel="nofollow" class="twitter-timeline-link" data-ultimate-url="http://m.mlb.com/apps">m.mlb.com/apps</a>)</p>
    <small><a href="https://twitter.com/_andrew_allen_/189494135999307776">2 May</a>     <span>via MLB.com At the Ballpark on iOS</span></small>
  </td>
</tr>



</tbody></table>

  </div>

</div>