<div id="myModal" class="modal hide fade">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h3>#Hashtag Details</h3>
  </div>
  <div class="modal-body">
    <div id="flot" style="width:420px;height:200px;"></div>
    <hr>
    <table id="context-tweets" style="width:100%;">
      <tbody>
        <tr>
          <td><h4>Tweets</h4></td>
        </tr>
      </tbody>
    </table>

  </div>

</div>