 <div id="myModal" class="modal hide fade">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h3>#Hashtag Details</h3>
  </div>
  <div class="modal-body">
    <div id="flot" style="width:420px;height:200px;"></div>
    

    <hr>

    <table id="user-table" style="width:100%;">
          <tbody><tr>
            <td><h4>Tweets</h4></td>
            
          </tr>
    <!-- <pre> -->
      <!-- </pre> -->
<tr style="border-top:1px solid #e8e8e8; border-bottom:1px solid #e8e8e8;">
  <td>
    <img src="http://a0.twimg.com/profile_images/2081263761/educated-dog-wearing-suit-and-tie_normal.jpeg">
  </td>
  <td>
    <div><strong>Andrew Allen </strong></div>
    here's a post with a <a href="https://twitter.com/search?q=%23hashtag">#hashtag</a><br>
    <small><a href="https://twitter.com/_andrew_allen_/190498630665383936">12 Apr</a>     <span>via web</span></small>
  </td>
</tr>



  <!-- <pre> -->
      <!-- </pre> -->
<tr style="border-top:1px solid #e8e8e8; border-bottom:1px solid #e8e8e8;">
  <td>
    <img src="http://a0.twimg.com/profile_images/2081263761/educated-dog-wearing-suit-and-tie_normal.jpeg">
  </td>
  <td>
    <div><strong>Andrew Allen </strong></div>
    here's another one<br>
    <small><a href="https://twitter.com/_andrew_allen_/189511565081456640">10 Apr</a>     <span>via web</span></small>
  </td>
</tr>



  <!-- <pre> -->
      <!-- </pre> -->
<tr style="border-top:1px solid #e8e8e8; border-bottom:1px solid #e8e8e8;">
  <td>
    <img src="http://a0.twimg.com/profile_images/2081263761/educated-dog-wearing-suit-and-tie_normal.jpeg">
  </td>
  <td>
    <div><strong>Andrew Allen </strong></div>
    I need a tweet to test a twitter app... so here it is<br>
    <small><a href="https://twitter.com/_andrew_allen_/189494135999307776">09 Apr</a>     <span>via web</span></small>
  </td>
</tr>



</tbody></table>

  </div>

</div>