<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#"><img src="logos/tweetsweep5.png" height="100" width="150"/></a>
      <div class="nav-collapse">
        <ul class="nav">
          {% for item in navigation %}
            {% if item.page == page %}
              {% set active = 'active' %}
            {% endif %}
            <li class="{{active}}"><a href="{{ item.href }}">{{ item.caption }}</a></li>
            {% set active = '' %}
          {% endfor %}
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>  